name    'counsyl-redis'
version '0.9.1'
source  'git://github.counsyl.com/dev/puppet-redis.git'
author  'Counsyl, Inc.'
license 'Apache License, Version 2.0'
summary 'Puppet module for installing and configuring a Redis server.'
description 'Puppet module for installing and configuring a Redis server.'
project_page 'https://github.counsyl.com/dev/puppet-redis'

dependency 'puppetlabs/stdlib', '>= 4.1.0'
