name    'counsyl-redis'
version '0.9.3'
source  'git://github.com/counsyl/puppet-redis.git'
author  'Counsyl, Inc.'
license 'Apache License, Version 2.0'
summary 'Puppet module for installing and configuring a Redis server.'
description 'Puppet module for installing and configuring a Redis server.'
project_page 'https://github.com/counsyl/puppet-redis'

dependency 'counsyl/sys', '>= 0.9.13'
